# Generated by Django 5.1.6 on 2025-03-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='cover_picture',
            field=models.ImageField(default='default_cover_pic.jpg', upload_to=''),
        ),
    ]
